name: gpg test
on: [ workflow_dispatch ]

jobs:
  run-gpg-test:
    name: Run GPG tests
    runs-on: ubuntu-latest
    steps:
      #- name: Checkout the repository
      #  uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Generate Maven project
        run: mvn -B -U archetype:generate -DgroupId=com.mycompany.app -DartifactId=my-app -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false
      - name: Create pom.xml
        run: |
          cat >my-app/pom.xml <<EOL
          <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
          <modelVersion>4.0.0</modelVersion>
          <groupId>com.mycompany.app</groupId>
          <artifactId>my-app</artifactId>
          <packaging>jar</packaging>
          <version>1.0-SNAPSHOT</version>
          <name>my-app</name>
          <url>http://maven.apache.org</url>
          <dependencies>
            <dependency>
              <groupId>junit</groupId>
              <artifactId>junit</artifactId>
              <version>3.8.1</version>
              <scope>test</scope>
            </dependency>
          </dependencies>
          <build>
            <plugins>
              <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <version>1.6</version>
                <executions>
                  <execution>
                    <id>sign-artifacts</id>
                    <phase>verify</phase>
                    <goals>
                      <goal>sign</goal>
                    </goals>
                    <configuration>
                      <gpgArguments>
                        <arg>--pinentry-mode</arg>
                        <arg>loopback</arg>
                      </gpgArguments>
                    </configuration>
                  </execution>
                </executions>
              </plugin>
            </plugins>
          </build>
          </project>
          EOL
      - name: Setup GPG
        env:
          KEYRING: ${{ secrets.KEYRING }}
        run: |
           gpg --batch --import "${KEYRING}"
           for fpr in $(gpg --list-keys --with-colons  | awk -F: \'/fpr:/ {print $10}\' | sort -u); do echo -e "5\ny\n" |  gpg --batch --command-fd 0 --expert --edit-key ${fpr} trust; done
      - name: Run Maven build
        run: mvn -B -f my-app/pom.xml clean verify
      - name: GPG verify
        run: gpg --verify my-app/target/my-app-1.0-SNAPSHOT.jar.asc
      
